name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
        cache-dependency-path: PSFrontAngular/package-lock.json
    
    - run: cd PSFrontAngular 
        npm ci
        npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
